const WORKER_URL="https://jr-youth-calendar-api.yoshy55.workers.dev";
const DEFAULT_TITLE="Jrユース・スケジュール";
const $=id=>document.getElementById(id);
const imageInput=$("imageInput"),yearInput=$("yearInput"),previewArea=$("previewArea"),previewImage=$("previewImage"),fileInfo=$("fileInfo"),analyzeButton=$("analyzeButton"),statusCard=$("statusCard"),statusMessage=$("statusMessage"),resultCard=$("resultCard"),resultSummary=$("resultSummary"),eventList=$("eventList"),clearButton=$("clearButton"),selectAllButton=$("selectAllButton"),deselectAllButton=$("deselectAllButton"),eventTemplate=$("eventTemplate"),duplicateWarning=$("duplicateWarning"),exportCard=$("exportCard"),calendarTitleInput=$("calendarTitleInput"),reminderSelect=$("reminderSelect"),includeSourceNote=$("includeSourceNote"),downloadIcsButton=$("downloadIcsButton"),exportMessage=$("exportMessage");
let selectedFile=null,sourceDocumentTitle="";
yearInput.value=new Date().getFullYear();

imageInput.addEventListener("change",()=>{selectedFile=imageInput.files?.[0]||null;if(!selectedFile){resetImage();return}if(!selectedFile.type.startsWith("image/")){showStatus("画像ファイルを選択してください。",true);resetImage();return}previewImage.src=URL.createObjectURL(selectedFile);previewArea.classList.remove("hidden");fileInfo.textContent=`${selectedFile.name} / ${formatBytes(selectedFile.size)} / ${selectedFile.type}`;analyzeButton.disabled=false;hideResults()});

analyzeButton.addEventListener("click",async()=>{if(!selectedFile)return;analyzeButton.disabled=true;showStatus("画像を準備しています…");hideExportMessage();try{const optimized=await resizeImage(selectedFile,1800,.88);showStatus("予定表を解析しています…\n少し時間がかかることがあります。");const response=await fetch(WORKER_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({year:Number(yearInput.value),mimeType:optimized.mimeType,imageBase64:optimized.dataUrl})});let data;try{data=await response.json()}catch{throw new Error(`サーバーから正しい応答を受け取れませんでした。HTTP ${response.status}`)}if(!response.ok||!data.ok)throw new Error(data.details||data.error||`HTTP ${response.status}`);sourceDocumentTitle=data.documentTitle||"";renderEvents(data);showStatus(`解析完了：「男」の予定を ${data.eventCount??data.events?.length??0} 件取得しました。`)}catch(error){console.error(error);showStatus(`解析できませんでした。\n${error instanceof Error?error.message:String(error)}`,true)}finally{analyzeButton.disabled=false}});

clearButton.addEventListener("click",()=>{imageInput.value="";resetImage();hideResults();statusCard.classList.add("hidden");hideExportMessage()});
selectAllButton.addEventListener("click",()=>setAll(true));
deselectAllButton.addEventListener("click",()=>setAll(false));

downloadIcsButton.addEventListener("click",()=>{hideExportMessage();const cards=[...document.querySelectorAll(".event-card")];const selected=cards.map(readEventCard).filter(e=>e.enabled);if(!selected.length){showExportMessage("出力する予定を1件以上選択してください。",true);return}const invalid=selected.filter(e=>!validateEvent(e));cards.forEach(card=>{const e=readEventCard(card);card.classList.toggle("invalid",e.enabled&&!validateEvent(e))});if(invalid.length){showExportMessage(`未入力または時刻不明の予定が ${invalid.length} 件あります。赤枠を修正するか終日予定を選んでください。`,true);return}const title=calendarTitleInput.value.trim()||DEFAULT_TITLE;const ics=buildIcs(selected,title,reminderSelect.value,includeSourceNote.checked);downloadTextFile(ics,`${safeFileName(title)}.ics`,"text/calendar;charset=utf-8");showExportMessage(`${selected.length}件の予定をICSファイルにまとめました。`)});

function renderEvents(data){eventList.innerHTML="";const events=Array.isArray(data.events)?data.events:[];resultSummary.textContent=`${data.year??yearInput.value}年${data.month?`${data.month}月`:""}／${events.length}件`;if(!events.length)eventList.innerHTML="<p>登録対象となる「男」の予定は見つかりませんでした。</p>";for(const event of events){const node=eventTemplate.content.cloneNode(true),card=node.querySelector(".event-card");card.querySelector(".event-date").value=event.date||"";card.querySelector(".event-start").value=event.startTime||"";card.querySelector(".event-end").value=event.endTime||"";card.querySelector(".event-location").value=event.location||"";card.querySelector(".event-team").value=event.team||"";card.querySelector(".event-open").value=event.keyOpen||"";card.querySelector(".event-close").value=event.keyClose||"";card.querySelector(".event-notes").value=event.notes||"";card.querySelector(".event-confidence").textContent=typeof event.confidence==="number"?`${Math.round(event.confidence*100)}%`:"―";card.querySelector(".time-warning").classList.toggle("hidden",!!(event.startTime&&event.endTime));wireEventCard(card);eventList.appendChild(node)}detectDuplicates();resultCard.classList.remove("hidden");exportCard.classList.remove("hidden");updateExportState();resultCard.scrollIntoView({behavior:"smooth",block:"start"})}

function wireEventCard(card){const enabled=card.querySelector(".event-enabled"),allDay=card.querySelector(".event-all-day"),start=card.querySelector(".event-start"),end=card.querySelector(".event-end");enabled.addEventListener("change",()=>{updateEventCardState(card);updateExportState()});allDay.addEventListener("change",()=>{start.disabled=allDay.checked;end.disabled=allDay.checked;card.querySelector(".time-warning").classList.toggle("hidden",allDay.checked||(start.value&&end.value));card.classList.remove("invalid");updateExportState();detectDuplicates()});card.querySelectorAll("input,textarea").forEach(field=>field.addEventListener("input",()=>{card.classList.remove("invalid");card.querySelector(".time-warning").classList.toggle("hidden",allDay.checked||(start.value&&end.value));detectDuplicates();updateExportState()}));updateEventCardState(card)}
function setAll(value){document.querySelectorAll(".event-enabled").forEach(input=>{input.checked=value;updateEventCardState(input.closest(".event-card"))});updateExportState()}
function updateEventCardState(card){card.classList.toggle("disabled",!card.querySelector(".event-enabled").checked)}
function readEventCard(card){return{card,enabled:card.querySelector(".event-enabled").checked,allDay:card.querySelector(".event-all-day").checked,date:card.querySelector(".event-date").value,startTime:card.querySelector(".event-start").value,endTime:card.querySelector(".event-end").value,location:card.querySelector(".event-location").value.trim(),team:card.querySelector(".event-team").value.trim(),keyOpen:card.querySelector(".event-open").value.trim(),keyClose:card.querySelector(".event-close").value.trim(),notes:card.querySelector(".event-notes").value.trim()}}
function validateEvent(e){if(!e.date)return false;if(e.allDay)return true;return !!(e.startTime&&e.endTime&&e.endTime>e.startTime)}
function updateExportState(){const n=[...document.querySelectorAll(".event-enabled")].filter(i=>i.checked).length;downloadIcsButton.disabled=!n;downloadIcsButton.textContent=n?`選択した${n}件をICSファイルにする`:"選択した予定をICSファイルにする"}
function detectDuplicates(){const cards=[...document.querySelectorAll(".event-card")],groups=new Map();cards.forEach(card=>{card.classList.remove("duplicate");card.querySelector(".duplicate-badge").classList.add("hidden");const e=readEventCard(card),key=[e.date,e.allDay?"ALLDAY":e.startTime,e.allDay?"":e.endTime,normalizeKey(e.location),normalizeKey(e.team)].join("|");if(!groups.has(key))groups.set(key,[]);groups.get(key).push(card)});let count=0;for(const group of groups.values())if(group.length>1){count+=group.length;group.forEach(card=>{card.classList.add("duplicate");card.querySelector(".duplicate-badge").classList.remove("hidden")})}duplicateWarning.classList.toggle("hidden",!count);duplicateWarning.textContent=count?`同じ日付・時刻・場所・枠に見える予定が ${count} 件あります。不要なものはチェックを外してください。`:""}

function buildIcs(events,title,reminder,addSource){const lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//JrYouthSchedule//JA","CALSCALE:GREGORIAN","METHOD:PUBLISH",`X-WR-CALNAME:${escapeIcs(title)}`,"X-WR-TIMEZONE:Asia/Tokyo"];for(const e of events){const desc=[e.team?`枠・チーム：${e.team}`:"","区分：男",e.keyOpen?`鍵当番・開：${e.keyOpen}`:"",e.keyClose?`鍵当番・閉：${e.keyClose}`:"",e.notes?`備考：${e.notes}`:"",sourceDocumentTitle?`元資料：${sourceDocumentTitle}`:"",addSource?"予定表画像から自動作成":""].filter(Boolean);lines.push("BEGIN:VEVENT",`UID:${createUid(e)}`,`DTSTAMP:${formatUtcDate(new Date())}`,`SUMMARY:${escapeIcs(title)}`);if(e.allDay){lines.push(`DTSTART;VALUE=DATE:${e.date.replaceAll("-","")}`,`DTEND;VALUE=DATE:${addDays(e.date,1).replaceAll("-","")}`)}else{lines.push(`DTSTART;TZID=Asia/Tokyo:${formatLocalDateTime(e.date,e.startTime)}`,`DTEND;TZID=Asia/Tokyo:${formatLocalDateTime(e.date,e.endTime)}`)}if(e.location)lines.push(`LOCATION:${escapeIcs(e.location)}`);if(desc.length)lines.push(`DESCRIPTION:${escapeIcs(desc.join("\n"))}`);if(reminder!=="none")lines.push("BEGIN:VALARM",`TRIGGER:-PT${Number(reminder)}M`,"ACTION:DISPLAY",`DESCRIPTION:${escapeIcs(title)}`,"END:VALARM");lines.push("END:VEVENT")}lines.push("END:VCALENDAR");return foldIcsLines(lines).join("\r\n")+"\r\n"}
function createUid(e){return `${simpleHash([e.date,e.startTime,e.endTime,e.location,e.team,Date.now(),Math.random()].join("-"))}@jr-youth-calendar`}
function simpleHash(t){let h=0;for(let i=0;i<t.length;i++)h=((h<<5)-h+t.charCodeAt(i))|0;return Math.abs(h).toString(36)}
function escapeIcs(v){return String(v??"").replace(/\\/g,"\\\\").replace(/\r?\n/g,"\\n").replace(/;/g,"\\;").replace(/,/g,"\\,")}
function foldIcsLines(lines){const out=[],enc=new TextEncoder();for(const line of lines){let rest=line;while(enc.encode(rest).length>73){let cut=Math.min(rest.length,73);while(cut>1&&enc.encode(rest.slice(0,cut)).length>73)cut--;out.push(rest.slice(0,cut));rest=" "+rest.slice(cut)}out.push(rest)}return out}
function formatLocalDateTime(d,t){return `${d.replaceAll("-","")}T${t.replace(":","")}00`}
function formatUtcDate(d){return d.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"Z")}
function addDays(s,n){const d=new Date(`${s}T00:00:00`);d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function downloadTextFile(text,name,type){const blob=new Blob(["\uFEFF",text],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function safeFileName(v){return v.replace(/[\\/:*?"<>|]/g,"_").trim()||"calendar"}
function normalizeKey(v){return String(v||"").replace(/\s+/g,"").toLowerCase()}
function showStatus(m,e=false){statusCard.classList.remove("hidden");statusMessage.textContent=m;statusMessage.classList.toggle("error",e)}
function showExportMessage(m,e=false){exportMessage.classList.remove("hidden");exportMessage.textContent=m;exportMessage.classList.toggle("error",e)}
function hideExportMessage(){exportMessage.classList.add("hidden");exportMessage.textContent="";exportMessage.classList.remove("error")}
function hideResults(){resultCard.classList.add("hidden");exportCard.classList.add("hidden");eventList.innerHTML="";duplicateWarning.classList.add("hidden")}
function resetImage(){selectedFile=null;previewImage.removeAttribute("src");previewArea.classList.add("hidden");fileInfo.textContent="";analyzeButton.disabled=true}
function formatBytes(b){if(b<1024)return `${b} B`;if(b<1048576)return `${(b/1024).toFixed(1)} KB`;return `${(b/1048576).toFixed(1)} MB`}
function resizeImage(file,max,q){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error("画像ファイルを読み込めませんでした。"));r.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error("画像を開けませんでした。"));img.onload=()=>{let w=img.naturalWidth,h=img.naturalHeight,largest=Math.max(w,h);if(largest>max){const s=max/largest;w=Math.round(w*s);h=Math.round(h*s)}const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d",{alpha:false});ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);resolve({dataUrl:c.toDataURL("image/jpeg",q),mimeType:"image/jpeg"})};img.src=String(r.result)};r.readAsDataURL(file)})}
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(console.error));
